SRC_NAME = afkey
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/stdoutsubc /usr/bin/stdoutsubc
	$(ROMFSINST) -p +x $(THISDIR)/afycx.sh /usr/bin/afycx.sh
	$(ROMFSINST) -p +x $(THISDIR)/bafa.sh /usr/bin/bafa.sh
